#!/usr/bin/env bash
# Install nginx web server
# Redirection

sudo apt-get  update -y
sudo apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
