#!/usr/bin/env bash
# A script to double number of web servers
apt-get  update ; apt-get -y install nginx

string="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$string/" /etc/nginx/nginx.conf
# restart nginx
sudo service nginx restart
